# Generated by Django 4.1.5 on 2023-02-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_employee',
            name='number_of_days',
        ),
    ]
