# Generated by Django 4.1.5 on 2023-02-15 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField()),
                ('emergency_contact_number', models.IntegerField()),
                ('address', models.TextField()),
                ('postion', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('martial_status', models.BooleanField(default=False)),
                ('blood_group', models.CharField(max_length=10)),
                ('job_title', models.CharField(max_length=250)),
                ('work_location', models.CharField(max_length=250)),
                ('date_of_joining', models.DateField(auto_now=True)),
                ('reporting_to', models.CharField(max_length=250)),
                ('linked_in', models.URLField(max_length=250)),
                ('profile_picture', models.ImageField(blank=True, upload_to='media/profile')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
