# Generated by Django 4.1.5 on 2023-02-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
